### ISSUE TITLE
Crash when viewing REI

### ISSUE THREAD

**Issue by xanthian** [theorbtwo/RoughlyEnoughResources#35]
[16:11:55] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Adding entry
	at net.minecraft.class_757.method_3192(class_757.java:883) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.12.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.5.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry.get(net.minecraft.class_3611)" because "net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry.INSTANCE" is null
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getStillTexture(FluidStackHooksImpl.java:126) ~[architectury-2.6.35.jar:?]
	at dev.architectury.hooks.fluid.FluidStackHooks.getStillTexture(FluidStackHooks.java) ~[architectury-2.6.35.jar:?]
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition$FluidEntryRenderer.getExtraData(FluidEntryDefinition.java:210) ~[RoughlyEnoughItems-6.1.319.jar:?]
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition$FluidEntryRenderer.getExtraData(FluidEntryDefinition.java:199) ~[RoughlyEnoughItems-6.1.319.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.add(BatchedEntryRendererManager.java:77) ~[RoughlyEnoughItems-6.1.319.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.addAll(BatchedEntryRendererManager.java:61) ~[RoughlyEnoughItems-6.1.319.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.<init>(BatchedEntryRendererManager.java:55) ~[RoughlyEnoughItems-6.1.319.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:274) ~[RoughlyEnoughItems-6.1.319.jar:?]
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:575) ~[RoughlyEnoughItems-6.1.319.jar:?]
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:496) ~[RoughlyEnoughItems-6.1.319.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:340) ~[RoughlyEnoughItems-6.1.319.jar:?]
	at net.minecraft.class_757.handler$zed000$renderScreenPost(class_757.java:1539) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:874) ~[intermediary-1.17.1.jar:?]
	... 10 more

actions.js:2804 ---- Minecraft Crash Report ----
// Don't do that.

Time: 06/11/2021, 16:11
Description: Adding entry

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry.get(net.minecraft.class_3611)" because "net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry.INSTANCE" is null
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getStillTexture(FluidStackHooksImpl.java:126)
	at dev.architectury.hooks.fluid.FluidStackHooks.getStillTexture(FluidStackHooks.java)
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition$FluidEntryRenderer.getExtraData(FluidEntryDefinition.java:210)
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition$FluidEntryRenderer.getExtraData(FluidEntryDefinition.java:199)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.add(BatchedEntryRendererManager.java:77)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.addAll(BatchedEntryRendererManager.java:61)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.<init>(BatchedEntryRendererManager.java:55)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:274)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:575)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:496)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:340)
	at net.minecraft.class_757.handler$zed000$renderScreenPost(class_757.java:1539)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getStillTexture(FluidStackHooksImpl.java:126)
	at dev.architectury.hooks.fluid.FluidStackHooks.getStillTexture(FluidStackHooks.java)

-- Screen details --
Details:
	Screen name: net.minecraft.class_3979
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:49)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:43)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.add(BatchedEntryRendererManager.java:90)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.addAll(BatchedEntryRendererManager.java:61)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.<init>(BatchedEntryRendererManager.java:55)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:274)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:575)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:496)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:340)
	at net.minecraft.class_757.handler$zed000$renderScreenPost(class_757.java:1539)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 0
	Entry type: minecraft:fluid
	Is empty: false
	Entry identifier: minecraft:water

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition
	Fluid Type: minecraft:water
	Fluid Amount: 81000
	Fluid NBT: null

-- Screen render details --
Details:
	Screen name: net.minecraft.class_3979
	Mouse location: Scaled: (494, 168). Absolute: (989.000000, 337.000000)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2.000000

Was viewing items from Continuity+ at the time, if thats any relevance.
Mod list attached
![image](https://user-images.githubusercontent.com/7688001/140616400-9ec3fee0-b0de-4e1c-a867-d8a7f68c6a19.png)

**Comment by xanthian** [comment]
I've put this against the wrong mod >.< should have been on REI
