### ISSUE TITLE
Crashes 1.18.2 forge

### ISSUE THREAD

**Issue by freopt** [theorbtwo/RoughlyEnoughResources#59]
[crash-2022-04-13_11.37.25-client.txt](https://github.com/theorbtwo/RoughlyEnoughResources/files/8483074/crash-2022-04-13_11.37.25-client.txt)
If I replace with JER it works fine

**Comment by theorbtwo** [comment]
I had a bit of a poke about, and this doesn't feel like an easy bug.  RER is using a fabric mixin in order to get a bit of data that the normal Minecraft API has, but only as a private attribute of a core object, with no accessor.  This is a perfectly reasonable thing to do, as RER is a fabric mod, because REI was at the time it was written.  So one solution is to declare either way if RER should support running under forge.  If we declare no, then we can close this bug as being your fault -- you tried to use RER in an unsupported situation.  If we declare yes, then we need to find a workaround that will make RER work as both a fabric and forge mod.  There is an older, uglier, version of the code which doesn't use a mixin, which might work.

Contrayrwise, it's possible that I'm barking up the wrong tree entirely, because the getFluid mixin isn't the only one RER requires, and if the other one wasn't there, I don't think anything would be calling getFluid.  This suggests that one of your other mods is doing something screwy with fluids.  

Do you have any mods, other than Pneumaticraft, that does interesting things with fluids?  Can you poke around at the REI interface and see if it has issues with any of the fluids?

**Comment by freopt** [comment]
I don't really understand the more technical parts of your comment, all I really know is that there is a version of RER on Curseforge marked as forge and that's what I used. 

In terms of fluid rendering in REI, the only problem I saw was that in all Immersive Engineering machines the actual fluid was rendered a tiny bit to the right of where it's supposed to be. 
![image](https://user-images.githubusercontent.com/45438411/163240416-a7bd3633-0059-4db8-af44-32e5a0df60e3.png)

**Comment by freopt** [comment]
Theres also this in the logs 

```txt
[13:43:39] [Render thread/ERROR]: Could not find parent mezz/jei/plugins/vanilla/ingredients/fluid/FluidStackRenderer for class me/haydenb/assemblylinemachines/plugins/jei/RecipeCategoryBuilder$1DynamicFluidStackRenderer in classloader cpw.mods.modlauncher.TransformingClassLoader@7e8279e5 on thread Thread[Render thread,10,main]
[13:43:39] [Render thread/ERROR]: An error occurred building event handler
java.lang.ClassNotFoundException: mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackRenderer
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.haydenb.assemblylinemachines.plugins.jei.RecipeCategoryBuilder.getBasicRenderer(RecipeCategoryBuilder.java:349) ~[assemblylinemachines-1.18.2-1.3.9.jar%2365!/:?]
	at me.haydenb.assemblylinemachines.plugins.jei.RecipeCategoryBuilder$1ALMRecipeCategory.setRecipe(RecipeCategoryBuilder.java:257) ~[assemblylinemachines-1.18.2-1.3.9.jar%2365!/:?]
	at me.haydenb.assemblylinemachines.plugins.jei.RecipeCategoryBuilder$1ALMRecipeCategory.setRecipe(RecipeCategoryBuilder.java:166) ~[assemblylinemachines-1.18.2-1.3.9.jar%2365!/:?]
	at me.shedaniel.rei.jeicompat.wrap.JEIDisplaySetup.create(JEIDisplaySetup.java:88) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at me.shedaniel.rei.jeicompat.wrap.JEIWrappedCategory.setupDisplay(JEIWrappedCategory.java:150) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at me.shedaniel.rei.jeicompat.wrap.JEIWrappedCategory.setupDisplay(JEIWrappedCategory.java:143) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at me.shedaniel.rei.jeicompat.wrap.JEIWrappedCategory.setupDisplay(JEIWrappedCategory.java:56) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.initDisplays(DefaultDisplayViewingScreen.java:265) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.m_7856_(DefaultDisplayViewingScreen.java:246) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:423) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:918) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at me.shedaniel.rei.impl.client.ClientHelperImpl.openView(ClientHelperImpl.java:313) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at me.shedaniel.rei.impl.client.ClientHelperImpl.openRecipeViewingScreen(ClientHelperImpl.java:280) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.lambda$init$13(DefaultDisplayViewingScreen.java:240) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at me.shedaniel.rei.impl.client.gui.widget.TabWidget.m_6375_(TabWidget.java:90) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.m_6375_(DefaultDisplayViewingScreen.java:502) ~[RoughlyEnoughItems-8.1.444.jar%23213!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2347!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2343!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2347!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1066) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23250!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.45.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

**Comment by devBoi76** [comment]
Hi, I'm having the same issue and crash. Using REI 8.2.470, forge 40.1.4 mc 1.18.2 tried RER 2.5.0 and 2.5.1

**Comment by 0x6273** [comment]
I get the same crash if I have REI 8.3.512, RER 2.5.1, and one of the following mods enabled:
- Create 0.5.0c
- Blood Magic 3.2.3-38
- Tinkers' Construct 3.5.1.31
