### ISSUE TITLE
Mod is incompatible with some datapacks, error "Invalid player data"

### ISSUE THREAD

**Issue by Blackilykat** [theorbtwo/RoughlyEnoughResources#60]
# Description
Whenever I try entering some of my worlds which have [this datapack](https://vanillatweaks.net/share#GN7Bfj) I get kicked out instantly with the error "Invalid player data". This issue does not happen once this mod is removed from my folder.
# Details
### Version
1.18.2
### Client
Fabric
### Mod version
2.5.0
### Other mods

- Cloth config 6.2.57
- Architectury API 4,0,30
- Fabric API 0,47,9
- Roughly Enogh Items 8,0.442

# Steps to reproduce

1. Start Minecraft with the mod
2. Click on Singleplayer
3. Click on Create new world
4. Click on Data packs and add [this datapack](https://vanillatweaks.net/share#GN7Bfj)
5. Create the world

# Log
```
[20:31:21] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[20:31:27] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:31:27] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:31:27] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:31:27] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:31:27] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:31:28] [Render thread/INFO]: Loaded 7 recipes
[20:31:28] [Render thread/WARN]: Found validation problem in {minecraft:entities/villager}.pools[0].entries[0]: Unknown loot table called minecraft:entities/reference/villager/villager_head
[20:31:28] [Render thread/INFO]: Loaded 1152 advancements
[20:31:29] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:31:29] [Render thread/INFO]: Applied 0 biome modifications to 0 of 61 new biomes in 385.4 ?s
[20:31:29] [Server thread/INFO]: Starting integrated minecraft server version 1.18.2
[20:31:29] [Server thread/INFO]: Generating keypair
[20:31:29] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:31:30] [Render thread/INFO]: Preparing spawn area: 0%
[20:31:31] [Render thread/INFO]: Preparing spawn area: 0%
[20:31:31] [Render thread/INFO]: Preparing spawn area: 0%
[20:31:31] [Render thread/INFO]: Preparing spawn area: 0%
[20:31:31] [Render thread/INFO]: Preparing spawn area: 0%
[20:31:32] [Render thread/INFO]: Preparing spawn area: 0%
[20:31:32] [Render thread/INFO]: Preparing spawn area: 0%
[20:31:33] [Render thread/INFO]: Preparing spawn area: 0%
[20:31:33] [Render thread/INFO]: Preparing spawn area: 4%
[20:31:34] [Render thread/INFO]: Preparing spawn area: 4%
[20:31:34] [Render thread/INFO]: Preparing spawn area: 6%
[20:31:35] [Render thread/INFO]: Preparing spawn area: 10%
[20:31:35] [Render thread/INFO]: Preparing spawn area: 13%
[20:31:36] [Render thread/INFO]: Preparing spawn area: 13%
[20:31:36] [Render thread/INFO]: Preparing spawn area: 34%
[20:31:37] [Render thread/INFO]: Preparing spawn area: 47%
[20:31:37] [Render thread/INFO]: Preparing spawn area: 56%
[20:31:38] [Render thread/INFO]: Preparing spawn area: 75%
[20:31:39] [Render thread/INFO]: Time elapsed: 9453 ms
[20:31:39] [Server thread/INFO]: Changing view distance to 7, from 10
[20:31:39] [Server thread/INFO]: Changing simulation distance to 5, from 0
[20:31:41] [Server thread/INFO]: Blackilykat[local:E:63c95e1a] logged in with entity id 6606 at (0.30000001192092896, 65.5, -2.003903729974357)
[20:31:41] [REI-ReloadPlugins/INFO]: Reloading Plugin Manager [REIPlugin] stage [START], registered 6 plugins: DefaultRuntimePlugin [roughlyenoughitems], DefaultClientRuntimePlugin [roughlyenoughitems], PluginEntry [roughlyenoughresources], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[20:31:41] [Server thread/INFO]: Blackilykat joined the game
[20:31:41] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIPlugin] with 2 entry types, 5 item comparators, 0 fluid comparators and 2 fluid support providers in 11ms.
[20:31:41] [REI-ReloadPlugins/INFO]: Reloading Plugin Manager [REIClientPlugin] stage [START], registered 3 plugins: DefaultClientRuntimePlugin [roughlyenoughitems], PluginEntry [roughlyenoughresources], DefaultClientPlugin [roughlyenoughitems]
[20:31:41] [Render thread/WARN]: Suppressing Reload Plugins of stage START
[20:31:41] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIClientPlugin] with 1371 entries, 5282 displays, 2 display visibility predicates, 26 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Fuel, Brewing, Composting, Stripping, Smithing, Anvil, Beacon Base, Beacon Payment, Tilling, Pathing, Waxing, Wax Scraping, Oxidizing, Oxidation Scraping, Information, Overworld Generation, The Nether Generation, The End Generation, Block Loot Drop, Entity Loot Drop), 4 exclusion zones and 3 overlay deciders in 146ms.
[20:31:41] [REI-ReloadPlugins/INFO]: Reloading Plugin Manager [REIServerPlugin] stage [START], registered 3 plugins: DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems]
[20:31:41] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIServerPlugin] with 4 menu infos in 3ms.
[20:31:41] [REI-ReloadPlugins/INFO]: Reloading Plugin Manager [REIPlugin] stage [END], registered 6 plugins: DefaultRuntimePlugin [roughlyenoughitems], DefaultClientRuntimePlugin [roughlyenoughitems], PluginEntry [roughlyenoughresources], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[20:31:41] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIPlugin] with 2 entry types, 5 item comparators, 0 fluid comparators and 2 fluid support providers in 9ms.
[20:31:41] [REI-ReloadPlugins/INFO]: Reloading Plugin Manager [REIClientPlugin] stage [END], registered 3 plugins: DefaultClientRuntimePlugin [roughlyenoughitems], PluginEntry [roughlyenoughresources], DefaultClientPlugin [roughlyenoughitems]
[20:31:41] [Render thread/INFO]: Refreshing cached entry list texture...
[20:31:41] [Render thread/INFO]: Refreshing cached entry list texture...
[20:31:41] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIClientPlugin] with 1371 entries, 5282 displays, 2 display visibility predicates, 26 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Fuel, Brewing, Composting, Stripping, Smithing, Anvil, Beacon Base, Beacon Payment, Tilling, Pathing, Waxing, Wax Scraping, Oxidizing, Oxidation Scraping, Information, The End Generation, The Nether Generation, Overworld Generation, Block Loot Drop, Entity Loot Drop), 4 exclusion zones and 3 overlay deciders in 171ms.
[20:31:41] [REI-ReloadPlugins/INFO]: Reloading Plugin Manager [REIServerPlugin] stage [END], registered 3 plugins: DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems]
[20:31:41] [REI-ReloadPlugins/INFO]: Reloaded Plugin Manager [REIServerPlugin] with 4 menu infos in 6ms.
[20:31:41] [Server thread/ERROR]: Couldn't place player in world
io.netty.handler.codec.EncoderException: String too big (was 34278 bytes encoded, max 32767)
	at net.minecraft.class_2540.method_10788(class_2540.java:519) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10814(class_2540.java:513) ~[client-intermediary.jar:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.writeJsonPrimitive(RoughlyEnoughResources.java:140) ~[rer-2.5.0.jar:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.writeJson(RoughlyEnoughResources.java:115) ~[rer-2.5.0.jar:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.writeJson(RoughlyEnoughResources.java:130) ~[rer-2.5.0.jar:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.writeJson(RoughlyEnoughResources.java:121) ~[rer-2.5.0.jar:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.writeJson(RoughlyEnoughResources.java:130) ~[rer-2.5.0.jar:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.writeJson(RoughlyEnoughResources.java:121) ~[rer-2.5.0.jar:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.writeJson(RoughlyEnoughResources.java:130) ~[rer-2.5.0.jar:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.writeJson(RoughlyEnoughResources.java:121) ~[rer-2.5.0.jar:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.writeJson(RoughlyEnoughResources.java:130) ~[rer-2.5.0.jar:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.sendLootToPlayers(RoughlyEnoughResources.java:53) ~[rer-2.5.0.jar:?]
	at net.minecraft.class_3324.handler$zlc000$onPlayerConnect(class_3324.java:2457) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$zgp000$handlePlayerJoin(class_3248.java:563) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20:31:41] [Server thread/INFO]: Blackilykat lost connection: Invalid player data
[20:31:41] [Server thread/INFO]: Blackilykat left the game
[20:31:41] [Server thread/INFO]: Stopping singleplayer server as player logged out
[20:31:41] [Server thread/INFO]: Stopping server
[20:31:41] [Server thread/INFO]: Saving players
[20:31:41] [Server thread/INFO]: Saving worlds
[20:31:43] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival :>]'/minecraft:overworld
[20:31:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival :>]'/minecraft:the_nether
[20:31:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Survival :>]'/minecraft:the_end
[20:31:44] [Server thread/INFO]: ThreadedAnvilChunkStorage (Survival __): All chunks are saved
[20:31:44] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20:31:44] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20:31:44] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
```

**Comment by ThinkWithPbody** [comment]
I've had this problem for the longest time and forgot to report it!

**Comment by Sunconure11** [comment]
Having this issue too.

@theorbtwo

**Comment by aelfwyne** [comment]
Same. Crashy crash.

**Comment by theDerxu** [comment]
PLEASE fix this.

**Comment by shanoaice** [comment]
This even affects Farmer's Delight, as its generated datapack seems to trigger this bug too.

**Comment by Lgmrszd** [comment]
Having same issue on All Of Fabric 6 (1.4.3), identical error in the log.
