### ISSUE TITLE
Conflict with unknown on 1.18.2 forge 

### ISSUE THREAD

**Issue by SettingDust** [theorbtwo/RoughlyEnoughResources#63]
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.material.FlowingFluid.m_76068_(boolean)" because the return value of "net.minecraft.world.level.block.LiquidBlock.getFluid()" is null
	at net.minecraft.world.level.block.LiquidBlock.initFluidStateCache(LiquidBlock.java:181) ~[client-1.18.2-20220404.173914-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:immersive_weathering.mixins.json:LiquidBlockMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.LiquidBlock.m_5888_(LiquidBlock.java:89) ~[client-1.18.2-20220404.173914-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:immersive_weathering.mixins.json:LiquidBlockMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.handler$bph003$init(BlockBehaviour.java:3399) ~[client-1.18.2-20220404.173914-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:epic_rei_lmao:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:byg.mixins.json:common.block.MixinBlockBehaviourBlockStateBase,pl:mixin:APP:passablefoliage.mixins.json:MixinBlockState,pl:mixin:APP:radium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:chunk.block_counting.AbstractBlockStateMixin,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60611_(BlockBehaviour.java) ~[client-1.18.2-20220404.173914-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:epic_rei_lmao:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:byg.mixins.json:common.block.MixinBlockBehaviourBlockStateBase,pl:mixin:APP:passablefoliage.mixins.json:MixinBlockState,pl:mixin:APP:radium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:chunk.block_counting.AbstractBlockStateMixin,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:518) ~[forge-1.18.2-40.1.48-universal.jar%23236!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:591) ~[forge-1.18.2-40.1.48-universal.jar%23236!/:?] {re:mixin,re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.registries.GameData.lambda$freezeData$9(GameData.java:297) ~[forge-1.18.2-40.1.48-universal.jar%23236!/:?] {re:mixin,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinGameData,pl:mixin:APP:kiwi.mixins.json:GameDataMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:295) ~[forge-1.18.2-40.1.48-universal.jar%23236!/:?] {re:mixin,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinGameData,pl:mixin:APP:kiwi.mixins.json:GameDataMixin,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$5(ForgeStatesProvider.java:33) ~[forge-1.18.2-40.1.48-universal.jar%23236!/:?] {re:classloading,pl:epic_rei_lmao:A}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:185) ~[fmlcore-1.18.2-40.1.48.jar%23232!/:?] {re:mixin}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:185) ~[fmlcore-1.18.2-40.1.48.jar%23232!/:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.lambda$finishMods$17(ModLoader.java:175) ~[fmlcore-1.18.2-40.1.48.jar%23232!/:?] {re:mixin}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:175) ~[fmlcore-1.18.2-40.1.48.jar%23232!/:?] {re:mixin}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$finishModLoading$6(ClientModLoader.java:126) ~[forge-1.18.2-40.1.48-universal.jar%23236!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinClientModLoader,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.1.48-universal.jar%23236!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinClientModLoader,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.finishModLoading(ClientModLoader.java:126) ~[forge-1.18.2-40.1.48-universal.jar%23236!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinClientModLoader,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$3(ClientModLoader.java:105) ~[forge-1.18.2-40.1.48-universal.jar%23236!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinClientModLoader,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```
https://pastes.dev/F5Rd857QzY

**Comment by AndreiTS** [comment]
Same error here.
Minecraft: 1.18.2
Forge: 40.1.41
REI: 8.2.492
RER: 2.5.1

https://paste.ee/p/51PKp
