### ISSUE TITLE
[1.19][Crash?] On server loading player into world

### ISSUE THREAD

**Issue by AubriTheHuman** [theorbtwo/RoughlyEnoughResources#67]
Issue where creating or loading a world with Roughly enough resources installed causes the world to fail to load the player, causing the server to hang (singleplayer both creation and loading, the server on player joining). Also prevents leaving the world and quitting the game as the server thread has failed. Unsure what's happening tbh, except for what I'm guessing is an incorrect mapping of some sort. But here are the logs for the error. 

This is in version "rer-2.6.0"

Crash snippet Pastebin: https://pastebin.com/uDMfWNxS
Full log Pastebin: https://pastebin.com/BSbMeVap

**Comment by RiffTopp** [comment]
I've been having the same problem, I launched it with just the dependencies, so I don't believe it's a compatibility issue

**Comment by xanthian** [comment]
```
  <log4j:Event logger="net.minecraft.class_3248" timestamp="1668882118269" level="ERROR" thread="Server thread">
    <log4j:Message><![CDATA[Couldn't place player in world]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2769.method_11899()" because "$$1" is null
	at net.minecraft.class_4488$class_4490.method_21899(class_4488.java:108)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.class_4488$class_4490.method_21901(class_4488.java:108)
	at net.minecraft.class_4488$class_4490.method_516(class_4488.java:102)
	at net.minecraft.class_5330$class_5333.serialize(class_5330.java:125)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at net.minecraft.class_85$class_90.method_442(class_85.java:141)
	at net.minecraft.class_77$class_78.method_412(class_77.java:43)
	at net.minecraft.class_77$class_78.method_422(class_77.java:40)
	at net.minecraft.class_79$class_5337.method_29320(class_79.java:80)
	at net.minecraft.class_79$class_5337.method_516(class_79.java:74)
	at net.minecraft.class_5330$class_5333.serialize(class_5330.java:125)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at net.minecraft.class_69$1.method_29314(class_69.java:56)
	at net.minecraft.class_69$1.method_422(class_69.java:53)
	at net.minecraft.class_79$class_5337.method_29320(class_79.java:80)
	at net.minecraft.class_79$class_5337.method_516(class_79.java:74)
	at net.minecraft.class_5330$class_5333.serialize(class_5330.java:125)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at net.minecraft.class_55$class_57.method_357(class_55.java:186)
	at net.minecraft.class_55$class_57.serialize(class_55.java:169)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at net.minecraft.class_52$class_54.method_339(class_52.java:240)
	at net.minecraft.class_52$class_54.serialize(class_52.java:210)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJsonTree(Gson.java:628)
	at com.google.gson.Gson.toJsonTree(Gson.java:607)
	at uk.me.desert_island.rer.RoughlyEnoughResources.sendLootToPlayers(RoughlyEnoughResources.java:53)
	at net.minecraft.class_3324.handler$ebo000$onPlayerConnect(class_3324.java:5506)
	at net.minecraft.class_3324.method_14570(class_3324.java:289)
	at net.minecraft.class_3248.method_33800(class_3248.java:151)
	at net.minecraft.class_3248.method_14384(class_3248.java:138)
	at net.minecraft.class_3248.redirect$bkc000$handlePlayerJoin(class_3248.java:563)
	at net.minecraft.class_3248.method_18784(class_3248.java:73)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Unknown Source)
]]></log4j:Throwable>
  </log4j:Event>
```

**Comment by TheUnknownCod3r** [comment]
Happens on Fabric, Switching out for Just enough Resources instead does fix the issue, interestingly. 

My Log: https://pastebin.com/5gYvQQSc

**Comment by inikishev** [comment]
https://gist.github.com/dpe0/5a8b0b829154190a8dd831a3b8dc1416
