### ISSUE TITLE
Invalid Player Data 1.19.2

### ISSUE THREAD

**Issue by FooterManDev** [theorbtwo/RoughlyEnoughResources#78]
RES prevents players from loading into worlds with an Invalid Player Data error. I saw that #73 mentioned the issue too, but not only is this issue on Forge, I couldn't find the PR they mentioned, so I think it's unrelated. 
I have not been able to confirm if this is an issue with the addon alone or mod compat, not enough time. Here's a [latest.log](https://gist.github.com/FooterMan14/dc75081a7ca8b22b9dd7519a331bc9e4) if that helps.

**Comment by unilock** [comment]
Unfortunately, most Forge mods remain inherently incompatible with REI (and its addons). The incompatible mod, in this case, is Farmer's Delight.

```
[26Jan2023 11:50:47.542] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
com.google.gson.JsonSyntaxException: Unknown type: vectorwing.farmersdelight.common.loot.function.CopySkilletFunction@46efbd15
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.serialize(GsonAdapterFactory.java:120) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%23121!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_7219_(LootPoolSingletonContainer.java:141) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7219_(LootItem.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7219_(LootItem.java:40) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_6170_(LootPoolEntryContainer.java:80) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_6170_(LootPoolEntryContainer.java:74) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.serialize(GsonAdapterFactory.java:125) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%23121!/:?]
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:187) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%23121!/:?]
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:279) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:253) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%23121!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%23121!/:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.sendLootToPlayers(RoughlyEnoughResources.java:53) ~[rer-2.6.1.jar%23350!/:?]
	at net.minecraft.server.players.PlayerList.handler$zdp000$onPlayerConnect(PlayerList.java:1452) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:247) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23377!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

You could *try* removing REI Plugin Compatibilities, which would prevent mods from loading their JEI plugins, if they have any. This might allow the game to finish loading the world, at the cost of removing Farmer's Delight JEI compat (in the form of its "skillet" recipes), along with every other JEI compatibility your installed mods implement.
This means, for the most part, that mods that add custom recipe viewer categories - macerating, mixing, etc. - will be entirely missing, leaving only vanilla's categories, such as crafting and smelting.

As for an actual fix - that remains beyond my knowledge :P

***

EDIT:

Related issues: #60 #67 #70

PR that fixes(?) the issue: https://github.com/theorbtwo/RoughlyEnoughResources/pull/69

Build for Fabric 1.18.2: https://github.com/vCybah/RoughlyEnoughResources/releases/tag/2.5.2-fix
Build for Fabric 1.19: https://github.com/Linguardium/RoughlyEnoughResources/releases/tag/1.19-primitiveStringFix

I'll test that PR on Forge 1.18.2, and update this with how that goes.

***

UPDATE: Looks like it's working!!
...for that issue, at least. There're still mods that don't play nice with RER for their own reasons :(
(one being Enigmatic Legacy, which i "fixed" by hackily cherry-picking [this commit](https://github.com/Aizistral-Studios/Enigmatic-Legacy/commit/857aa211318873180761aaa01a132a43cb0ac36e) into the 1.18.X branch. ymmv!)
(next up: Mana and Artifice... curse you, ARR!)

***

EDIT: Oops, that PR doesn't actually fix *this* issue - I thought it did because I stopped getting the same error with Farmer's Delight on my end, but it turns out I just had other mods having the same issue before Farmer's Delight was able to load...

There's an open issue on Farmer's Delight's bug tracker here:
https://github.com/vectorwing/FarmersDelight/issues/565
